### ISSUE TITLE
Can't export with texture

### ISSUE THREAD

**Issue by dirtlordthezombieking** [Dancovich/libgdx_blender_g3d_exporter#24]
Not sure if this is even still active but I have a problem that is probably just a settings issue.

I'm using this plug-in conveniently the version it's compatible with is the last version compatible with my dell dimension dinosaur. but every time I try to export my model with textures it throws this error:

Traceback (most recent call last):
 File "c:\...\io_scene_g3d_\g3d_exporter.py", line 116, in execute
  return self.startExport(context)
 File "c:\...\io_scene_g3d_\profile.py", line 33, in profile_fun
  return fun(*arts, **kwargs)
 File "c:\...\io_scene_g3d_\g3d_exporter.py", line 140, in startExport
  materials = self.generateMaterials(context)
 File "c:\...\io_scene_g3d_\profile.py", line 33, in profile_fun
  return fun(*arts, **kwargs)
 File "c:\...\io_scene_g3d_\g3d_exporter.py", line 495, in generateMaterials
  util.debug("found texture {!s}. texture coords are {!s}, texture type is {!s}", slot.name, slot.texture_coords, slot.texture.type)
AttributeError: 'NoneType' object has no Attribute 'type'

location: <unknown location>:-1

**Comment by vittfiles** [comment]
Hi.
Did you try a png format to see if the error occurs with any type?

**Comment by dirtlordthezombieking** [comment]
I use only PNG for textures, also I was able to export a few other models with textures, it's just this one throwing the error. it's a bit more complex than the others but I can't see that making a difference.
